# Site wide configuration

title: RPi Tinkering
locale: en_US
description: A blog of my experiences, failures and moderate successes tinkering with a Raspberry Pi. Learning python, linux, ruby and the virtue of trial and error along the way
logo: site-logo.png
search: true
url: http://localhost:4040

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Philip De Keulenaer
  avatar: bio-photo.jpg
  email: philip.dekeulenaer@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: pdekeulenaer
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: