# Site settings
title: RPi Tinkering
description: > # this means to ignore newlines until "baseurl:"
  A blog of my experiences, good and bad, with the Raspberry Pi and the collection of hobby projects it enables
  Think music streaming, python learning, webserver building,...
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  pdekeulenaer

# Build settings
markdown: kramdown
